# Generated by Django 4.2.5 on 2023-09-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_img_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ccis_username',
        ),
    ]
